### ISSUE TITLE
JSON example

### ISSUE THREAD

**Issue by carlhunterroach** [HyperBrain/serverless-models-plugin#1]
In addition to the YAML examples for defining a Model it'd be handy to give a JSON example. One could then see what was required and also where the format differs from that entered directly into API Gateway.

**Comment by HyperBrain** [comment]
Good catch. I will update the README accordingly.

**Comment by HyperBrain** [comment]
I added the JSON examples. The fix will be published in the next days.
I also added the '$schema' property, so that validators will work properly but I think the 'title' property can be set, but will not do anything as the schema definition name in the models file defines the model name implicitly. Nevertheless it should not break anything if you set it - this way one could just paste the APIG models into the models file and vice versa.
